# environment.yml
channels:
- conda-forge
dependencies:
- python =3.8
- radiant-mlhub =0.5.3
- tifffile =2019.7.26.2
- pandas =1.2.0
- matplotlib =3.3.4
- rasterio =1.1.8
- tqdm =4.64.0
- pip
- pip:
  - py-entangle